export const goalForm = {
  SHORT_DESCRIPTION: 'SHORT_DESCRIPTION',
  BIG_DESCRIPTION: 'BIG_DESCRIPTION',
  ACTIVITIES: 'ACTIVITIES',
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  DELETE_ACTIVITY: 'DELETE_ACTIVITY',
  ACTIVITY_NAME: 'ACTIVITY_NAME',
  ACTIVITY_DAYS: 'ACTIVITY_DAYS',
  SELECT_ALL_DAYS: 'SELECT_ALL_DAYS',
  UNSELECT_ALL_DAYS: 'UNSELECT_ALL_DAYS',
  EMPTY_ACTIVITY: 'EMPTY_ACTIVITY',
  REWARDS: 'REWARDS',
  ADD_REWARD: 'ADD_REWARD',
  DELETE_REWARD: 'DELETE_REWARD',
  WEEKLY_REWARD: 'WEEKLY_REWARD',
  END: 'END',
  EMPTY_FORM: 'EMPTY_FORM'
}
